// ===== PRO-FAB 3D CLOUD CONFIG =====
// Fill in your JSONBin.io credentials below.
// Every device that opens this site will automatically sync orders & products.
// Get a free account at https://jsonbin.io — then paste your Master Key and Bin ID here.

window.PROFAB_CONFIG = {
  cloudKey: '$2a$10$JDUtUr0CN1vkr0NbpD6GF.6K3U/YdqiJ/i4e8HGkDRz4JbFgMlBtK',
  cloudBin: '69c48961aa77b81da91d825d',

  // Admin password hash & salt — generated by Admin → Settings → Change Password.
  // Paste the values shown there here. All devices will then use the same credentials.
  adminSalt: '',
  adminHash: ''
};
