// ===== PRO-FAB 3D CONFIG =====
// Stripe publishable key — starts with pk_live_ or pk_test_
// Get it from dashboard.stripe.com → Developers → API Keys

window.PROFAB_CONFIG = {
  // Admin password hash & salt — generated by Admin → Settings → Change Password.
  // Paste the values shown there here so all devices use the same credentials on first load.
  adminSalt: 'c72dde47002c655a8c60c5369b162319',
  adminHash: 'd7a18117ad2ec65284ff76e884233e3eeb69ff0404ccb617939a0544a5691a54',

  // Stripe publishable key (safe for browser)
  stripeKey: '',

  // JSONBin cloud storage
  cloudKey: '$2a$10$JDUtUr0CN1vkr0NbpD6GF.6K3U/YdqiJ/i4e8HGkDRz4JbFgMlBtK',
  cloudBin: '69c48961aa77b81da91d825d',
};
